<?php
// This file is automatically generated by scripts/sync-index-php.mjs. Do not edit directly.
?>
<!DOCTYPE html>
<html lang="no">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Fjolsenbanden – Fargerikt gaming-community</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@500;600;700;800;900&display=swap" rel="stylesheet" />
    <style>
      body {
        font-family: 'Nunito', system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
        background-color: #050b24;
        color: #ffffff;
      }

      a {
        color: inherit;
      }

      .partners {
        margin: 5rem auto 0;
        max-width: 64rem;
        border-radius: 2.5rem;
        border: 1px solid rgba(255, 255, 255, 0.12);
        background: rgba(4, 17, 73, 0.7);
        padding: 3rem 2rem;
        text-align: center;
        box-shadow: 0 24px 48px rgba(6, 14, 35, 0.45);
        backdrop-filter: blur(6px);
      }

      .partners h2 {
        margin-bottom: 1rem;
        font-size: clamp(1.875rem, 3vw, 2.5rem);
        font-weight: 700;
        color: #ffffff;
      }

      .partners p {
        margin: 0 auto;
        max-width: 42rem;
        color: rgba(224, 231, 255, 0.85);
        line-height: 1.6;
      }

      .partners p + p {
        margin-top: 1.5rem;
      }

      .partner-logos {
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
        gap: 1.5rem;
        margin: 2rem auto 0;
      }

      .partner-logos img {
        height: 4.5rem;
        width: auto;
        max-width: 12rem;
        object-fit: contain;
        opacity: 0.9;
        transition: transform 0.2s ease, opacity 0.2s ease;
      }

      .partner-logos img:hover {
        opacity: 1;
        transform: scale(1.03);
      }

      .partners .cta {
        display: inline-flex;
        align-items: center;
        justify-content: center;
        margin-top: 1.5rem;
        padding: 0.75rem 1.75rem;
        border-radius: 9999px;
        font-weight: 600;
        background: linear-gradient(90deg, #13a0f9, #ff2f9c);
        color: #ffffff;
        box-shadow: 0 16px 32px rgba(19, 160, 249, 0.35);
        text-decoration: none;
        transition: transform 0.2s ease, box-shadow 0.2s ease, opacity 0.2s ease;
      }

      .partners .cta:hover {
        transform: translateY(-2px);
        box-shadow: 0 20px 40px rgba(19, 160, 249, 0.45);
        opacity: 0.95;
      }
    </style>
  </head>
  <body class="flex min-h-screen flex-col text-white">
    <div id="fjolsenbanden-home" class="flex flex-1 flex-col">
      <div class="relative flex flex-1 flex-col overflow-x-hidden bg-gradient-to-b from-[#131A49] via-[#0B163F] to-[#050B24] text-white">
<div class="pointer-events-none fixed inset-0 -z-10 opacity-60" style="background:radial-gradient(circle at 18% 12%, rgba(19,160,249,0.3), transparent 55%), radial-gradient(circle at 80% 0%, rgba(255,47,156,0.18), transparent 50%)">
</div>
<nav class="relative sticky top-0 z-50 border-b border-white/10 bg-[#050B24]/80 backdrop-blur">
<div class="mx-auto hidden w-full max-w-6xl items-center gap-6 px-6 py-4 md:grid md:grid-cols-[1fr_auto_1fr]">
<div class="hidden items-center justify-end gap-6 md:flex">
<ul class="flex items-center gap-6 text-sm font-medium">
<li>
<a class="transition-colors duration-150 hover:text-[#13A0F9]" href="#">Hjem</a>
</li>
<li>
<a class="transition-colors duration-150 hover:text-[#13A0F9]" href="#live">Live</a>
</li>
<li>
<a class="transition-colors duration-150 hover:text-[#13A0F9]" href="#medlemskap">Medlemskap</a>
</li>
</ul>
</div>
<a class="flex items-center gap-3 text-white md:justify-self-center" href="#" aria-label="Fjolsenbanden hjem">
            <img src="/assets/branding/Liggende-Lys.svg" alt="FJOLSENBANDEN logo" class="h-8 w-auto max-w-[180px] sm:h-10 md:h-12"/>
<span class="hidden text-lg font-semibold sm:block">FJOLSENBANDEN</span>
</a>
<div class="hidden items-center justify-start gap-6 md:flex">
<ul class="flex items-center gap-6 text-sm font-medium">
<li>
<a class="transition-colors duration-150 hover:text-[#13A0F9]" href="#premier">Premier</a>
</li>
<li>
<a class="transition-colors duration-150 hover:text-[#13A0F9]" href="#sponsorer">Samarbeid</a>
</li>
<li>
<a class="transition-colors duration-150 hover:text-[#13A0F9]" href="#kontakt">Kontakt</a>
</li>
</ul>
<a href="#bli-medlem" class="inline-flex items-center gap-2 rounded-full border border-white/20 px-6 py-3 font-semibold text-white transition hover:border-white/40 hover:bg-white/10">Bli medlem</a>
</div>
</div>
<div class="mx-auto flex w-full max-w-6xl items-center justify-between px-6 py-4 md:hidden">
<a class="flex items-center gap-3 text-white" href="#" aria-label="Fjolsenbanden hjem">
                <img src="/assets/branding/Liggende-Lys.svg" alt="FJOLSENBANDEN logo" class="h-8 w-auto max-w-[180px] sm:h-10"/>
<span class="hidden text-lg font-semibold sm:block">FJOLSENBANDEN</span>
</a>
<div class="flex items-center gap-3">
<button type="button" aria-expanded="false" aria-controls="mobile-navigation" aria-label="Åpne meny" class="inline-flex h-11 w-11 items-center justify-center rounded-full border border-white/20 text-white transition hover:border-white/40 hover:bg-white/10 focus:outline-none focus:ring-2 focus:ring-white/40">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-menu h-5 w-5" aria-hidden="true">
<line x1="4" x2="20" y1="12" y2="12">
</line>
<line x1="4" x2="20" y1="6" y2="6">
</line>
<line x1="4" x2="20" y1="18" y2="18">
</line>
</svg>
</button>
</div>
</div>
<div id="mobile-navigation" class="absolute left-0 right-0 top-full z-[60] mt-3 px-6 md:hidden hidden">
<div class="rounded-2xl border border-white/10 bg-[#101c37] p-4 shadow-[0_18px_42px_rgba(12,21,45,0.45)]">
<ul class="flex flex-col gap-2 text-sm font-medium text-white/80">
<li>
<a class="block rounded-lg px-4 py-2 transition hover:bg-white/10 hover:text-white" href="#">Hjem</a>
</li>
<li>
<a class="block rounded-lg px-4 py-2 transition hover:bg-white/10 hover:text-white" href="#live">Live</a>
</li>
<li>
<a class="block rounded-lg px-4 py-2 transition hover:bg-white/10 hover:text-white" href="#medlemskap">Medlemskap</a>
</li>
<li>
<a class="block rounded-lg px-4 py-2 transition hover:bg-white/10 hover:text-white" href="#premier">Premier</a>
</li>
<li>
<a class="block rounded-lg px-4 py-2 transition hover:bg-white/10 hover:text-white" href="#sponsorer">Samarbeid</a>
</li>
<li>
<a class="block rounded-lg px-4 py-2 transition hover:bg-white/10 hover:text-white" href="#kontakt">Kontakt</a>
</li>
</ul>
<a href="#bli-medlem" class="mt-4 block rounded-full border border-white/20 px-4 py-2 text-center font-semibold text-white transition hover:border-white/40 hover:bg-white/10">Bli medlem</a>
</div>
</div>
</nav>
<header class="relative z-10 pb-40">
<section id="community" class="mt-6 px-6">
<div class="mx-auto grid max-w-6xl gap-10 lg:grid-cols-2 lg:items-start">
<div class="space-y-6">
<div class="space-y-4 text-center lg:text-left">
<h1 class="text-4xl font-extrabold sm:text-5xl">Velkommen til <span class="text-[#13A0F9]">FJOLSENBANDEN</span>
</h1>
<p class="text-base text-zinc-300 sm:text-lg">Spillglede for hele familien – trygge streams, turneringer og premier.</p>
</div>
<div class="space-y-4 rounded-3xl border border-white/10 bg-white/5 p-6 text-left shadow-[0_18px_42px_rgba(12,21,45,0.45)]">
<h2 class="text-xl font-semibold text-[#13A0F9]">🎮 Hva er FjOlsenbanden?</h2>
<p class="text-sm leading-relaxed text-zinc-200 sm:text-base">FjOlsenbanden er et raskt voksende gaming-community med over 2500 medlemmer på Discord, 3200++ følgere på Twitch og 4200++ på TikTok – både barn, ungdom og foreldre!</p>
<p class="text-sm leading-relaxed text-zinc-200 sm:text-base">
<span class="font-semibold text-white">Målet vårt er enkelt:</span>
<br class="hidden sm:block"/>Å skape et trygt, positivt og inkluderende miljø der alle kan game uten hets, mobbing eller negativ adferd.</p>
<p class="text-sm leading-relaxed text-zinc-200 sm:text-base">FjOlsen bruker mange timer hver uke på å arrangere konkurranser, turneringer og aktiviteter for medlemmene – alltid med fellesskap, spilleglede og respekt i sentrum.</p>
</div>
</div>
<div class="flex w-full max-w-xl flex-col items-center gap-6 lg:items-start">
<div class="relative w-full overflow-hidden rounded-3xl border border-white/10 shadow-[0_28px_60px_rgba(7,12,28,0.6)]">
<iframe class="aspect-video w-full" width="560" height="315" src="https://www.youtube.com/embed/8EgRIkmvmtM?si=qMzmEaMfP-2ODMbc" title="YouTube video player" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowfullscreen="">
</iframe>
</div>
<div class="w-full rounded-3xl border border-white/10 bg-[#101c37]/80 p-5 shadow-[0_18px_42px_rgba(12,21,45,0.45)]">
<div class="mb-3 flex items-center gap-2 text-sm font-semibold uppercase tracking-wide text-white/80">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-shield-check h-4 w-4 text-[#13A0F9]">
<path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z">
</path>
<path d="m9 12 2 2 4-4">
</path>
</svg> Følg FjOlsenbanden</div>
<div class="flex flex-wrap justify-center gap-2 sm:justify-start">
<a href="https://www.twitch.tv/FjOlsenFN" target="_blank" rel="noopener noreferrer" class="flex items-center gap-2 rounded-full border border-white/10 bg-white/10 px-3 py-1.5 text-xs font-medium uppercase tracking-wide text-white/90 transition duration-200 hover:-translate-y-0.5 hover:bg-white/20 hover:text-white focus:outline-none focus:ring-2 focus:ring-[#13A0F9] active:scale-95">
<span class="text-white/90">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-twitch h-5 w-5" aria-hidden="true">
<path d="M21 2H3v16h5v4l4-4h5l4-4V2zm-10 9V7m5 4V7">
</path>
</svg>
</span>
<span>Twitch</span>
</a>
<a href="https://youtube.com/@fjolsenbanden" target="_blank" rel="noopener noreferrer" class="flex items-center gap-2 rounded-full border border-white/10 bg-white/10 px-3 py-1.5 text-xs font-medium uppercase tracking-wide text-white/90 transition duration-200 hover:-translate-y-0.5 hover:bg-white/20 hover:text-white focus:outline-none focus:ring-2 focus:ring-[#13A0F9] active:scale-95">
<span class="text-white/90">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-youtube h-5 w-5" aria-hidden="true">
<path d="M2.5 17a24.12 24.12 0 0 1 0-10 2 2 0 0 1 1.4-1.4 49.56 49.56 0 0 1 16.2 0A2 2 0 0 1 21.5 7a24.12 24.12 0 0 1 0 10 2 2 0 0 1-1.4 1.4 49.55 49.55 0 0 1-16.2 0A2 2 0 0 1 2.5 17">
</path>
<path d="m10 15 5-3-5-3z">
</path>
</svg>
</span>
<span>YouTube</span>
</a>
<a href="https://www.tiktok.com/@fjolsenbanden" target="_blank" rel="noopener noreferrer" class="flex items-center gap-2 rounded-full border border-white/10 bg-white/10 px-3 py-1.5 text-xs font-medium uppercase tracking-wide text-white/90 transition duration-200 hover:-translate-y-0.5 hover:bg-white/20 hover:text-white focus:outline-none focus:ring-2 focus:ring-[#13A0F9] active:scale-95">
<span class="text-white/90">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-smartphone h-5 w-5" aria-hidden="true">
<rect width="14" height="20" x="5" y="2" rx="2" ry="2">
</rect>
<path d="M12 18h.01">
</path>
</svg>
</span>
<span>TikTok</span>
</a>
<a href="https://www.instagram.com/fjolsenbanden" target="_blank" rel="noopener noreferrer" class="flex items-center gap-2 rounded-full border border-white/10 bg-white/10 px-3 py-1.5 text-xs font-medium uppercase tracking-wide text-white/90 transition duration-200 hover:-translate-y-0.5 hover:bg-white/20 hover:text-white focus:outline-none focus:ring-2 focus:ring-[#13A0F9] active:scale-95">
<span class="text-white/90">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-instagram h-5 w-5" aria-hidden="true">
<rect width="20" height="20" x="2" y="2" rx="5" ry="5">
</rect>
<path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z">
</path>
<line x1="17.5" x2="17.51" y1="6.5" y2="6.5">
</line>
</svg>
</span>
<span>Instagram</span>
</a>
<a href="https://discord.gg/fjolsenbanden" target="_blank" rel="noopener noreferrer" class="flex items-center gap-2 rounded-full border border-white/10 bg-white/10 px-3 py-1.5 text-xs font-medium uppercase tracking-wide text-white/90 transition duration-200 hover:-translate-y-0.5 hover:bg-white/20 hover:text-white focus:outline-none focus:ring-2 focus:ring-[#13A0F9] active:scale-95">
<span class="text-white/90">
<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false" class="h-5 w-5" fill="currentColor">
<path d="M20.317 4.369a19.791 19.791 0 0 0-4.885-1.515.074.074 0 0 0-.079.037c-.211.375-.444.864-.608 1.249-1.844-.276-3.68-.276-5.486 0-.163-.407-.415-.874-.626-1.249a.077.077 0 0 0-.079-.037 19.736 19.736 0 0 0-4.885 1.515.07.07 0 0 0-.032.028C2.205 9.045 1.588 13.58 2.014 18.059a.082.082 0 0 0 .031.056 19.9 19.9 0 0 0 5.993 3.047.079.079 0 0 0 .084-.028c.461-.63.873-1.295 1.226-1.994a.077.077 0 0 0-.041-.105c-.652-.247-1.273-.549-1.872-.892a.078.078 0 0 1-.008-.13c.125-.094.25-.192.37-.291a.074.074 0 0 1 .077-.01c3.927 1.793 8.18 1.793 12.061 0a.074.074 0 0 1 .078.01c.12.099.245.198.37.291a.078.078 0 0 1-.008.13 13.09 13.09 0 0 1-1.873.892.077.077 0 0 0-.04.105c.36.699.772 1.364 1.225 1.994a.079.079 0 0 0 .084.028 19.876 19.876 0 0 0 6.002-3.047.077.077 0 0 0 .03-.055c.5-5.177-.838-9.673-3.548-13.662a.061.061 0 0 0-.031-.028Zm-12.052 9.91c-1.18 0-2.158-1.085-2.158-2.419 0-1.333.955-2.418 2.158-2.418 1.213 0 2.182 1.095 2.158 2.418-.001 1.334-.955 2.419-2.158 2.419Zm7.472 0c-1.18 0-2.158-1.085-2.158-2.419 0-1.333.955-2.418 2.158-2.418 1.213 0 2.182 1.095 2.158 2.418 0 1.334-.945 2.419-2.158 2.419Z">
</path>
</svg>
</span>
<span>Discord</span>
</a>
</div>
<p class="mt-3 text-center text-xs text-zinc-400 sm:text-left">Neste livesending starter 20:00 med co-op i Mario Kart og premier fra Lenovo!</p>
</div>
</div>
</div>
</section>
</header>
<main class="flex flex-col gap-28 pb-24">
<section id="hva-er" class="px-6" style="order:0">
<div class="mx-auto grid max-w-6xl gap-12 lg:grid-cols-2 lg:items-center">
<div class="space-y-6">
<h2 class="text-3xl font-bold sm:text-4xl">🎮 Hva er FjOlsenbanden?</h2>
<p class="text-lg text-slate-200">FjOlsenbanden er et raskt voksende gaming-community med over 2 500 medlemmer på Discord, 3 200+ følgere på Twitch og 4 200+ på TikTok. Her møtes barn, ungdom og foreldre for å game trygt sammen.</p>
<p class="text-lg text-slate-200">Målet vårt er enkelt: å skape et inkluderende miljø der alle kan spille uten hets, mobbing eller negativ adferd. FjOlsen legger ned mange timer hver uke på konkurranser, turneringer og aktiviteter – alltid med fellesskap og spilleglede i sentrum.</p>
<div class="rounded-3xl border border-white/10 bg-white/5 p-6 shadow-lg">
<p class="text-base text-slate-200">🎥 Se videoen til høyre for å møte FjOlsen og bli kjent med communityet!</p>
</div>
</div>
<div class="relative overflow-hidden rounded-3xl border border-white/10 bg-black/60 shadow-2xl">
<iframe width="100%" height="315" src="https://www.youtube.com/embed/P01NkLOA39A?si=LYD3IVf5SSZrehsJ" title="Møt FjOlsen" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerPolicy="strict-origin-when-cross-origin" allowfullscreen="" class="h-full min-h-[280px] w-full">
</iframe>
</div>
</div>
</section>
<section id="live" class="px-6" style="order:1">
<div class="mx-auto grid max-w-6xl gap-12 rounded-[2.5rem] border border-white/5 bg-gradient-to-br from-[#121a4b]/80 via-[#10153b]/80 to-[#0c122d]/80 p-12 shadow-2xl lg:grid-cols-[1.1fr_0.9fr]">
<div class="space-y-6">
<h2 class="text-3xl font-bold sm:text-4xl">📈 Følg FjOlsenbanden</h2>
<p class="text-lg text-slate-200">Totalt over 10 000 følgere på tvers av alle plattformer! Finn oss der du liker å se gaming-innhold – og bli en del av et hyggelig og støttende fellesskap.</p>
<div class="grid gap-4 sm:grid-cols-3">
<div class="rounded-2xl border border-white/10 bg-white/5 p-4 text-center">
<p class="text-2xl font-bold text-cyan-300">2 500+</p>
<p class="text-sm text-slate-300">Discord</p>
</div>
<div class="rounded-2xl border border-white/10 bg-white/5 p-4 text-center">
<p class="text-2xl font-bold text-cyan-300">3 200+</p>
<p class="text-sm text-slate-300">Twitch</p>
</div>
<div class="rounded-2xl border border-white/10 bg-white/5 p-4 text-center">
<p class="text-2xl font-bold text-cyan-300">4 200+</p>
<p class="text-sm text-slate-300">TikTok</p>
</div>
</div>
<div class="flex flex-wrap gap-3">
<a href="https://discord.gg/fjolsenbanden" class="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-4 py-2 text-sm font-medium text-white/90 transition hover:bg-white/20" rel="noreferrer" target="_blank">
<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false" class="h-4 w-4" fill="currentColor">
<path d="M20.317 4.369a19.791 19.791 0 0 0-4.885-1.515.074.074 0 0 0-.079.037c-.211.375-.444.864-.608 1.249-1.844-.276-3.68-.276-5.486 0-.163-.407-.415-.874-.626-1.249a.077.077 0 0 0-.079-.037 19.736 19.736 0 0 0-4.885 1.515.07.07 0 0 0-.032.028C2.205 9.045 1.588 13.58 2.014 18.059a.082.082 0 0 0 .031.056 19.9 19.9 0 0 0 5.993 3.047.079.079 0 0 0 .084-.028c.461-.63.873-1.295 1.226-1.994a.077.077 0 0 0-.041-.105c-.652-.247-1.273-.549-1.872-.892a.078.078 0 0 1-.008-.13c.125-.094.25-.192.37-.291a.074.074 0 0 1 .077-.01c3.927 1.793 8.18 1.793 12.061 0a.074.074 0 0 1 .078.01c.12.099.245.198.37.291a.078.078 0 0 1-.008.13 13.09 13.09 0 0 1-1.873.892.077.077 0 0 0-.04.105c.36.699.772 1.364 1.225 1.994a.079.079 0 0 0 .084.028 19.876 19.876 0 0 0 6.002-3.047.077.077 0 0 0 .03-.055c.5-5.177-.838-9.673-3.548-13.662a.061.061 0 0 0-.031-.028Zm-12.052 9.91c-1.18 0-2.158-1.085-2.158-2.419 0-1.333.955-2.418 2.158-2.418 1.213 0 2.182 1.095 2.158 2.418-.001 1.334-.955 2.419-2.158 2.419Zm7.472 0c-1.18 0-2.158-1.085-2.158-2.419 0-1.333.955-2.418 2.158-2.418 1.213 0 2.182 1.095 2.158 2.418 0 1.334-.945 2.419-2.158 2.419Z">
</path>
</svg>
<span>Discord</span>
</a>
<a href="https://www.twitch.tv/FjOlsenFN" class="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-4 py-2 text-sm font-medium text-white/90 transition hover:bg-white/20" rel="noreferrer" target="_blank">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-twitch h-4 w-4" aria-hidden="true">
<path d="M21 2H3v16h5v4l4-4h5l4-4V2zm-10 9V7m5 4V7">
</path>
</svg>
<span>Twitch</span>
</a>
<a href="https://youtube.com/@fjolsenbanden" class="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-4 py-2 text-sm font-medium text-white/90 transition hover:bg-white/20" rel="noreferrer" target="_blank">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-youtube h-4 w-4" aria-hidden="true">
<path d="M2.5 17a24.12 24.12 0 0 1 0-10 2 2 0 0 1 1.4-1.4 49.56 49.56 0 0 1 16.2 0A2 2 0 0 1 21.5 7a24.12 24.12 0 0 1 0 10 2 2 0 0 1-1.4 1.4 49.55 49.55 0 0 1-16.2 0A2 2 0 0 1 2.5 17">
</path>
<path d="m10 15 5-3-5-3z">
</path>
</svg>
<span>YouTube</span>
</a>
<a href="https://www.tiktok.com/@fjolsenbanden" class="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-4 py-2 text-sm font-medium text-white/90 transition hover:bg-white/20" rel="noreferrer" target="_blank">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-smartphone h-4 w-4" aria-hidden="true">
<rect width="14" height="20" x="5" y="2" rx="2" ry="2">
</rect>
<path d="M12 18h.01">
</path>
</svg>
<span>TikTok</span>
</a>
<a href="https://www.instagram.com/fjolsenbanden" class="inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-4 py-2 text-sm font-medium text-white/90 transition hover:bg-white/20" rel="noreferrer" target="_blank">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-instagram h-4 w-4" aria-hidden="true">
<rect width="20" height="20" x="2" y="2" rx="5" ry="5">
</rect>
<path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z">
</path>
<line x1="17.5" x2="17.51" y1="6.5" y2="6.5">
</line>
</svg>
<span>Instagram</span>
</a>
</div>
<div class="rounded-3xl border border-white/10 bg-white/5 p-6 text-sm text-slate-200">🎥 Se FjOlsen LIVE! Til venstre: Stream-vindu. Til høyre: Chat-feed. 👉 Følg oss her: Discord · Twitch · YouTube · TikTok · Instagram</div>
</div>
<div class="grid gap-6 lg:grid-cols-[minmax(0,2fr)_minmax(0,1fr)]">
<div class="space-y-4">
<div class="relative overflow-hidden rounded-2xl border border-white/10 bg-black/70 p-6">
<span class="inline-flex items-center gap-2 rounded-full bg-rose-500/20 px-3 py-1 text-xs font-semibold text-rose-200">🔴 Live preview</span>
<p class="mt-4 text-sm text-slate-300">Stream-vindu – se FjOlsen ta communityet gjennom nye utfordringer og konkurranser.</p>
<div class="mt-4 overflow-hidden rounded-xl border border-white/10 bg-black/80">
<!-- Dynamisk Twitch-embed med fallback -->
<div id="playerWrap" class="relative bg-black aspect-video rounded-2xl overflow-hidden">
  <div id="fallback" class="absolute inset-0 grid place-items-center text-center p-6">
    <div>
      <img id="thumb" class="w-full max-w-md mx-auto rounded-lg border border-white/10" alt="Twitch forhåndsvisning">
      <p class="mt-3 text-zinc-300 text-sm">Hvis spilleren ikke vises, åpne streamen direkte på Twitch.</p>
      <a id="cta" target="_blank" rel="noopener" class="inline-block mt-4 px-6 py-2 rounded-full bg-gradient-to-r from-[#13A0F9] to-[#FF2F9C]
                font-semibold text-white shadow-[0_0_20px_rgba(19,160,249,0.35)] hover:from-[#0d8bd6] hover:to-[#e12585] transition">
        Åpne på Twitch
      </a>
    </div>
  </div>
</div>
</div>
<script>
(() => {
  const channel = "FjOlsenFN";
  const parentHost = location.hostname || "localhost";
  const src = `https://player.twitch.tv/?channel=${encodeURIComponent(channel)}&parent=${encodeURIComponent(parentHost)}&muted=false&autoplay=true`;

  const iframe = document.createElement("iframe");
  iframe.src = src;
  iframe.allowFullscreen = true;
  iframe.className = "absolute inset-0 w-full h-full border-0";
  const wrap = document.getElementById("playerWrap");
  if (!wrap) return;
  wrap.appendChild(iframe);

  const thumb = document.getElementById("thumb");
  const cta = document.getElementById("cta");
  if (thumb) thumb.src = `https://static-cdn.jtvnw.net/previews-ttv/live_user_${channel}-640x360.jpg`;
  if (cta) cta.href = `https://www.twitch.tv/${channel}`;

  let loaded = false;
  iframe.addEventListener("load", () => {
    loaded = true;
    const fallback = document.getElementById("fallback");
    if (fallback) fallback.style.display = "none";
  });
  setTimeout(() => {
    if (!loaded) console.warn("Twitch embed ble blokkert — viser fallback.");
  }, 5000);
})();
</script>
<p class="mt-3 text-xs text-slate-400">Oppdater lenken i adminpanelet for å endre hvilken Twitch-kanal som vises.</p>
</div>
<div class="flex max-h-[640px] flex-col rounded-2xl border border-white/10 bg-[#1f2940] p-4">
<h3 class="mb-3 flex items-center gap-2 font-semibold text-[#13A0F9]">Live chat</h3>
<div id="custom-chat" class="flex-1 overflow-y-auto space-y-2 pr-1 text-sm"></div>
</div>
<div class="rounded-2xl border border-white/10 bg-black/60 p-6 lg:col-span-2">
<p class="text-xs font-semibold uppercase tracking-[0.3em] text-slate-400">Fellesskap</p>
<p class="mt-4 text-sm text-slate-200">Vi holder chatten trygg med dedikerte moderatorer og tydelige regler mot hets, mobbing og negativ adferd.</p>
</div>
</div>
<script src="https://unpkg.com/tmi.js@1.8.5/dist/tmi.min.js"></script>
<script>
(() => {
  const channel = "FjOlsenFN";
  const el = document.getElementById("custom-chat");
  const maxItems = 200;

  if (!el) return;

  const client = new tmi.Client({
    connection: { secure: true, reconnect: true },
    channels: [channel],
  });

  client.connect().catch(console.error);

  function addMsg({ user, text, color }) {
    const item = document.createElement("div");
    item.className = "rounded-lg bg-white/5 px-3 py-2";

    const name = document.createElement("span");
    name.className = "mr-2 font-semibold";
    name.style.color = color || "#13A0F9";
    name.textContent = user;

    const body = document.createElement("span");
    body.className = "text-slate-200";
    body.textContent = text;

    item.appendChild(name);
    item.appendChild(body);
    el.appendChild(item);

    while (el.children.length > maxItems) {
      el.removeChild(el.firstChild);
    }
    el.scrollTop = el.scrollHeight;
  }

  client.on("message", (channel, tags, message, self) => {
    if (self) return;
    addMsg({
      user: tags["display-name"] || tags.username,
      text: message,
      color: tags.color,
    });
  });

  client.on("connected", () =>
    addMsg({ user: "System", text: "Tilkoblet Twitch-chat ✅", color: "#4ade80" })
  );
  client.on("disconnected", () =>
    addMsg({ user: "System", text: "Frakoblet fra chat ❌", color: "#f87171" })
  );
})();
</script>
</section>
<section id="bli-medlem" class="px-6" style="order:0">
<div class="mx-auto max-w-6xl rounded-[2.5rem] border border-white/10 bg-white/5 p-12 shadow-2xl">
<h2 class="text-3xl font-bold sm:text-4xl">Bli medlem</h2>
<p class="mt-4 text-lg text-slate-200">Det er gratis å bli medlem i FjOlsenbanden! Alle kan delta i konkurranser, men for å vinne premier må du være registrert medlem.</p>
<p class="mt-6 text-base text-slate-200 sm:text-lg">Velg alder for å bli med:</p>
<div class="mt-6 flex flex-wrap gap-4">
<a href="https://forms.gle/sq4mUf7s6e6UY7R58" class="inline-flex items-center gap-3 rounded-2xl bg-indigo-500 px-6 py-4 text-lg font-semibold text-white shadow-[0_12px_30px_rgba(99,102,241,0.45)] transition hover:bg-indigo-400">🔵 Under 18 år</a>
<a href="https://forms.gle/ZrbXCggnUY8FTT7t9" class="inline-flex items-center gap-3 rounded-2xl bg-emerald-500 px-6 py-4 text-lg font-semibold text-white shadow-[0_12px_30px_rgba(16,185,129,0.45)] transition hover:bg-emerald-400">🟢 Over 18 år</a>
</div>
</div>
</section>
<section id="samarbeid" class="px-6" style="order:4">
<div class="mx-auto max-w-6xl space-y-8">
<h2 class="text-3xl font-bold sm:text-4xl">🤝 Samarbeidspartnere</h2>
<p class="text-lg text-slate-200">Vi har allerede samarbeidet med flere kjente merkevarer – og vi er alltid på utkikk etter nye partnere som ønsker synlighet mot et engasjert gaming-publikum.</p>
<div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
<div class="flex items-center justify-center rounded-2xl border border-white/10 bg-white/5 shadow-[0_12px_24px_rgba(8,18,40,0.35)] transition hover:bg-white/10 h-60 w-full px-4 py-3">
<img src="https://setaei.com/Fjolsen/lenova.jpg" alt="Lenovo" class="h-full w-full object-contain" loading="lazy"/>
</div>
<div class="flex items-center justify-center rounded-2xl border border-white/10 bg-white/5 shadow-[0_12px_24px_rgba(8,18,40,0.35)] transition hover:bg-white/10 h-60 w-full px-4 py-3">
<img src="https://setaei.com/Fjolsen/samsung.jpg" alt="Samsung" class="h-full w-full object-contain" loading="lazy"/>
</div>
<div class="flex items-center justify-center rounded-2xl border border-white/10 bg-white/5 shadow-[0_12px_24px_rgba(8,18,40,0.35)] transition hover:bg-white/10 h-60 w-full px-4 py-3">
<img src="https://setaei.com/Fjolsen/philips.jpg" alt="Philips" class="h-full w-full object-contain" loading="lazy"/>
</div>
<div class="flex items-center justify-center rounded-2xl border border-white/10 bg-white/5 shadow-[0_12px_24px_rgba(8,18,40,0.35)] transition hover:bg-white/10 h-60 w-full px-4 py-3">
<img src="/assets/partners/komplett.svg" alt="Komplett.no" class="h-full w-full object-contain" loading="lazy"/>
</div>
</div>
</div>
</section>
<section id="live-chat" class="px-6" style="order:1">
<div class="mx-auto max-w-6xl">
<div class="flex max-h-[640px] flex-col rounded-2xl border border-white/10 bg-[#1f2940] p-4">
<h3 class="mb-3 flex items-center gap-2 font-semibold text-[#13A0F9]">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-message-circle h-4 w-4">
<path d="M7.9 20A9 9 0 1 0 4 16.1L2 22Z">
</path>
</svg> Live chat</h3>
<div class="flex-1 space-y-3 overflow-y-auto pr-1 text-sm">
<div class="rounded-lg bg-white/5 px-3 py-2">
<span class="mr-2 font-semibold text-[#13A0F9]">Lina</span>
<span class="text-zinc-200">Haha, den bossen var vilt!</span>
</div>
<div class="rounded-lg bg-white/5 px-3 py-2">
<span class="mr-2 font-semibold text-[#13A0F9]">Jonas</span>
<span class="text-zinc-200">Gleder meg til premie-trekningen 🔥</span>
</div>
<div class="rounded-lg bg-white/5 px-3 py-2">
<span class="mr-2 font-semibold text-[#13A0F9]">Sara</span>
<span class="text-zinc-200">Hei fra TikTok 😎</span>
</div>
<div class="rounded-lg bg-white/5 px-3 py-2">
<span class="mr-2 font-semibold text-[#13A0F9]">Marius</span>
<span class="text-zinc-200">Bra lyd i dag!</span>
</div>
</div>
<input type="text" placeholder="Skriv en kommentar..." class="mt-3 w-full rounded-lg border border-white/20 bg-white/10 px-3 py-2 text-sm text-white placeholder-zinc-400 outline-none focus:ring-2 focus:ring-[#13A0F9]"/>
</div>
</div>
</section>
<section id="medlemskap" class="mt-20 px-6 text-center" style="order:2">
<h2 class="mb-4 text-3xl font-bold">Velg medlemskap</h2>
<p class="mx-auto mb-8 max-w-2xl text-zinc-300">Bli med i konkurranser, streams og fellesskapet vårt på noen få klikk.</p>
<div class="mx-auto grid max-w-7xl gap-8 md:grid-cols-3">
<div class="rounded-2xl border border-zinc-200 bg-white shadow-sm rounded-2xl border bg-[#1f2940] shadow-lg transition-transform hover:-translate-y-1 border-green-400/40 ring-green-400/50">
<div class="p-6">
<h3 class="text-lg font-semibold flex items-center gap-2 text-white">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-gift h-6 w-6">
<rect x="3" y="8" width="18" height="4" rx="1">
</rect>
<path d="M12 8v13">
</path>
<path d="M19 12v7a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2v-7">
</path>
<path d="M7.5 8a2.5 2.5 0 0 1 0-5A4.8 8 0 0 1 12 8a4.8 8 0 0 1 4.5-5 2.5 2.5 0 0 1 0 5">
</path>
</svg> Gratismedlem</h3>
</div>
<div class="px-6 pb-6 space-y-4">
<div class="text-3xl font-bold text-white">0 kr / mnd</div>
<ul class="space-y-2 text-sm text-zinc-300">
<li class="flex items-center gap-2">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-trophy h-4 w-4 text-[#13A0F9]">
<path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6">
</path>
<path d="M18 9h1.5a2.5 2.5 0 0 0 0-5H18">
</path>
<path d="M4 22h16">
</path>
<path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22">
</path>
<path d="M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22">
</path>
<path d="M18 2H6v7a6 6 0 0 0 12 0V2Z">
</path>
</svg> Tilgang til Discord-serveren</li>
<li class="flex items-center gap-2">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-trophy h-4 w-4 text-[#13A0F9]">
<path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6">
</path>
<path d="M18 9h1.5a2.5 2.5 0 0 0 0-5H18">
</path>
<path d="M4 22h16">
</path>
<path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22">
</path>
<path d="M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22">
</path>
<path d="M18 2H6v7a6 6 0 0 0 12 0V2Z">
</path>
</svg> Delta på community-events</li>
<li class="flex items-center gap-2">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-trophy h-4 w-4 text-[#13A0F9]">
<path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6">
</path>
<path d="M18 9h1.5a2.5 2.5 0 0 0 0-5H18">
</path>
<path d="M4 22h16">
</path>
<path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22">
</path>
<path d="M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22">
</path>
<path d="M18 2H6v7a6 6 0 0 0 12 0V2Z">
</path>
</svg> Få nyheter og oppdateringer først</li>
</ul>
<button type="button" class="inline-flex items-center justify-center font-semibold transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-60 bg-zinc-900 text-white hover:bg-zinc-800 focus-visible:ring-zinc-900 h-11 px-6 text-base rounded-2xl w-full rounded-full bg-gradient-to-r from-[#13A0F9] to-[#FF2F9C] font-semibold text-white shadow-[0_16px_28px_rgba(19,160,249,0.35)] transition hover:from-[#0d8bd6] hover:to-[#e12585]">Velg</button>
</div>
</div>
<div class="rounded-2xl border border-zinc-200 bg-white shadow-sm rounded-2xl border bg-[#1f2940] shadow-lg transition-transform hover:-translate-y-1 border-cyan-400/40 ring-cyan-400/50">
<div class="p-6">
<h3 class="text-lg font-semibold flex items-center gap-2 text-white">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-gift h-6 w-6">
<rect x="3" y="8" width="18" height="4" rx="1">
</rect>
<path d="M12 8v13">
</path>
<path d="M19 12v7a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2v-7">
</path>
<path d="M7.5 8a2.5 2.5 0 0 1 0-5A4.8 8 0 0 1 12 8a4.8 8 0 0 1 4.5-5 2.5 2.5 0 0 1 0 5">
</path>
</svg> Turneringsmedlem</h3>
</div>
<div class="px-6 pb-6 space-y-4">
<div class="text-3xl font-bold text-white">79 kr / mnd</div>
<ul class="space-y-2 text-sm text-zinc-300">
<li class="flex items-center gap-2">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-trophy h-4 w-4 text-[#13A0F9]">
<path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6">
</path>
<path d="M18 9h1.5a2.5 2.5 0 0 0 0-5H18">
</path>
<path d="M4 22h16">
</path>
<path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22">
</path>
<path d="M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22">
</path>
<path d="M18 2H6v7a6 6 0 0 0 12 0V2Z">
</path>
</svg> Alt i Gratismedlem</li>
<li class="flex items-center gap-2">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-trophy h-4 w-4 text-[#13A0F9]">
<path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6">
</path>
<path d="M18 9h1.5a2.5 2.5 0 0 0 0-5H18">
</path>
<path d="M4 22h16">
</path>
<path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22">
</path>
<path d="M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22">
</path>
<path d="M18 2H6v7a6 6 0 0 0 12 0V2Z">
</path>
</svg> Delta i eksklusive turneringer</li>
<li class="flex items-center gap-2">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-trophy h-4 w-4 text-[#13A0F9]">
<path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6">
</path>
<path d="M18 9h1.5a2.5 2.5 0 0 0 0-5H18">
</path>
<path d="M4 22h16">
</path>
<path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22">
</path>
<path d="M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22">
</path>
<path d="M18 2H6v7a6 6 0 0 0 12 0V2Z">
</path>
</svg> Premier fra partnere hver måned</li>
</ul>
<button type="button" class="inline-flex items-center justify-center font-semibold transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-60 bg-zinc-900 text-white hover:bg-zinc-800 focus-visible:ring-zinc-900 h-11 px-6 text-base rounded-2xl w-full rounded-full bg-gradient-to-r from-[#13A0F9] to-[#FF2F9C] font-semibold text-white shadow-[0_16px_28px_rgba(19,160,249,0.35)] transition hover:from-[#0d8bd6] hover:to-[#e12585]">Velg</button>
</div>
</div>
<div class="rounded-2xl border border-zinc-200 bg-white shadow-sm rounded-2xl border bg-[#1f2940] shadow-lg transition-transform hover:-translate-y-1 border-amber-400/40 ring-amber-400/50">
<div class="p-6">
<h3 class="text-lg font-semibold flex items-center gap-2 text-white">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-gift h-6 w-6">
<rect x="3" y="8" width="18" height="4" rx="1">
</rect>
<path d="M12 8v13">
</path>
<path d="M19 12v7a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2v-7">
</path>
<path d="M7.5 8a2.5 2.5 0 0 1 0-5A4.8 8 0 0 1 12 8a4.8 8 0 0 1 4.5-5 2.5 2.5 0 0 1 0 5">
</path>
</svg> Pro-medlem</h3>
</div>
<div class="px-6 pb-6 space-y-4">
<div class="text-3xl font-bold text-white">149 kr / mnd</div>
<ul class="space-y-2 text-sm text-zinc-300">
<li class="flex items-center gap-2">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-trophy h-4 w-4 text-[#13A0F9]">
<path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6">
</path>
<path d="M18 9h1.5a2.5 2.5 0 0 0 0-5H18">
</path>
<path d="M4 22h16">
</path>
<path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22">
</path>
<path d="M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22">
</path>
<path d="M18 2H6v7a6 6 0 0 0 12 0V2Z">
</path>
</svg> Alt i Turneringsmedlem</li>
<li class="flex items-center gap-2">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-trophy h-4 w-4 text-[#13A0F9]">
<path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6">
</path>
<path d="M18 9h1.5a2.5 2.5 0 0 0 0-5H18">
</path>
<path d="M4 22h16">
</path>
<path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22">
</path>
<path d="M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22">
</path>
<path d="M18 2H6v7a6 6 0 0 0 12 0V2Z">
</path>
</svg> Coaching fra FjOlsen og teamet</li>
<li class="flex items-center gap-2">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-trophy h-4 w-4 text-[#13A0F9]">
<path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6">
</path>
<path d="M18 9h1.5a2.5 2.5 0 0 0 0-5H18">
</path>
<path d="M4 22h16">
</path>
<path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22">
</path>
<path d="M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22">
</path>
<path d="M18 2H6v7a6 6 0 0 0 12 0V2Z">
</path>
</svg> Tilgang til lukkede arrangementer</li>
</ul>
<button type="button" class="inline-flex items-center justify-center font-semibold transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-60 bg-zinc-900 text-white hover:bg-zinc-800 focus-visible:ring-zinc-900 h-11 px-6 text-base rounded-2xl w-full rounded-full bg-gradient-to-r from-[#13A0F9] to-[#FF2F9C] font-semibold text-white shadow-[0_16px_28px_rgba(19,160,249,0.35)] transition hover:from-[#0d8bd6] hover:to-[#e12585]">Velg</button>
</div>
</div>
</div>
</section>
<section id="premier" class="partners px-6" style="order:3">
<h2>Samarbeidspartnere</h2>
<p>Vi har allerede hatt samarbeid med flere kjente merkevarer.</p>
<div id="sponsorer" class="partner-logos">
<img src="/assets/partners/lenovo.svg" alt="Lenovo" loading="lazy"/>
<img src="/assets/partners/komplett.svg" alt="Komplett" loading="lazy"/>
<img src="/assets/partners/philips.svg" alt="Philips" loading="lazy"/>
<img src="/assets/partners/samsung.svg" alt="Samsung" loading="lazy"/>
</div>
<p>Ønsker du å synliggjøre din merkevare for vårt engasjerte gaming-publikum?</p>
<a href="#kontakt" class="cta">Kontakt oss</a>
</section>
<section id="tilbud" class="mt-20 px-6">
<div class="mx-auto max-w-6xl space-y-6 rounded-3xl border border-white/10 bg-white/5 p-8 text-center shadow-[0_24px_48px_rgba(6,14,35,0.45)]">
<div class="space-y-3">
<h2 class="text-3xl font-bold text-white">Andre tilbud</h2>
<p class="text-lg text-zinc-200">FjOlsenbanden tilbyr mer enn bare streaming!</p>
</div>
<div class="grid gap-6 text-left sm:grid-cols-2">
<div class="flex h-full flex-col gap-4 rounded-2xl border border-white/10 bg-[#101a33]/80 p-6 shadow-[0_16px_32px_rgba(6,14,35,0.45)]">
<div class="flex items-center gap-3">
<span class="grid h-12 w-12 place-content-center rounded-xl bg-gradient-to-br from-[#13A0F9] to-[#FF2F9C] text-black">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-mic h-6 w-6">
<path d="M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3Z">
</path>
<path d="M19 10v2a7 7 0 0 1-14 0v-2">
</path>
<line x1="12" x2="12" y1="19" y2="22">
</line>
</svg>
</span>
<h3 class="text-xl font-semibold text-white">Foredrag</h3>
</div>
<p class="text-sm leading-relaxed text-zinc-300">FjOlsen besøker skoler, idrettslag og e-sportklubber for å snakke om streaming, gaming-kultur og nettvett.</p>
</div>
<div class="flex h-full flex-col gap-4 rounded-2xl border border-white/10 bg-[#101a33]/80 p-6 shadow-[0_16px_32px_rgba(6,14,35,0.45)]">
<div class="flex items-center gap-3">
<span class="grid h-12 w-12 place-content-center rounded-xl bg-gradient-to-br from-[#13A0F9] to-[#FF2F9C] text-black">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-calendar-days h-6 w-6">
<path d="M8 2v4">
</path>
<path d="M16 2v4">
</path>
<rect width="18" height="18" x="3" y="4" rx="2">
</rect>
<path d="M3 10h18">
</path>
<path d="M8 14h.01">
</path>
<path d="M12 14h.01">
</path>
<path d="M16 14h.01">
</path>
<path d="M8 18h.01">
</path>
<path d="M12 18h.01">
</path>
<path d="M16 18h.01">
</path>
</svg>
</span>
<h3 class="text-xl font-semibold text-white">Events</h3>
</div>
<p class="text-sm leading-relaxed text-zinc-300">Vi arrangerer gaming-konkurranser for bedrifter, skoler og klubber – både digitalt og fysisk.</p>
</div>
<div class="flex h-full flex-col gap-5 rounded-2xl border border-white/10 bg-gradient-to-br from-[#161f33] via-[#101a33] to-[#0a1329] p-6 shadow-[0_20px_36px_rgba(6,14,35,0.55)]">
<div class="flex items-center gap-3">
<span class="grid h-12 w-12 place-content-center rounded-xl bg-gradient-to-br from-[#13A0F9] to-[#FF2F9C] text-black">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-box h-6 w-6">
<path d="M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z">
</path>
<path d="m3.3 7 8.7 5 8.7-5">
</path>
<path d="M12 22V12">
</path>
</svg>
</span>
<div>
<h3 class="text-xl font-semibold text-white">Unboxing</h3>
<p class="text-sm text-zinc-300">FjOlsen lager profesjonelle unboxing-videoer av dine produkter som kan brukes i deres markedsføring og deles med vårt community.</p>
</div>
</div>
<div class="space-y-4 rounded-2xl border border-pink-400/30 bg-pink-500/10 p-5 text-left text-pink-100/90">
<p class="text-base font-semibold text-white">🎯 Potensiell rekkevidde: <span class="text-2xl text-[#FFB7E5]">9 900+</span> kjøpsvillige følgere ser oss hver uke.</p>
<p class="text-sm text-pink-100/80">Vi aktiverer communityet på tvers av plattformene våre, slik at produktet ditt får både hype og salgsmuligheter allerede første dag.</p>
<div class="grid gap-3 sm:grid-cols-3">
<div class="rounded-xl bg-black/30 px-4 py-3 text-center text-xs uppercase tracking-wide text-pink-100/80">
<p class="text-lg font-semibold text-white">2 500+</p>
<p>Discord</p>
</div>
<div class="rounded-xl bg-black/30 px-4 py-3 text-center text-xs uppercase tracking-wide text-pink-100/80">
<p class="text-lg font-semibold text-white">3 200+</p>
<p>Twitch</p>
</div>
<div class="rounded-xl bg-black/30 px-4 py-3 text-center text-xs uppercase tracking-wide text-pink-100/80">
<p class="text-lg font-semibold text-white">4 200+</p>
<p>TikTok</p>
</div>
</div>
</div>
<button type="button" class="inline-flex items-center justify-center font-semibold transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-60 bg-zinc-900 text-white hover:bg-zinc-800 focus-visible:ring-zinc-900 h-11 px-6 text-base rounded-2xl rounded-full bg-gradient-to-r from-[#13A0F9] to-[#FF2F9C] font-semibold text-white shadow-[0_16px_28px_rgba(19,160,249,0.35)] transition hover:from-[#0d8bd6] hover:to-[#e12585]">Se unboxing-eksempel</button>
<p class="text-xs text-zinc-400">Trykk på knappen for å se en full unboxing-produksjon slik samarbeidspartnerne våre får den levert.</p>
</div>
<div class="flex h-full flex-col gap-4 rounded-2xl border border-white/10 bg-[#101a33]/80 p-6 shadow-[0_16px_32px_rgba(6,14,35,0.45)]">
<div class="flex items-center gap-3">
<span class="grid h-12 w-12 place-content-center overflow-hidden rounded-xl bg-gradient-to-br from-[#13A0F9] to-[#FF2F9C] p-1.5" aria-hidden="true">
<img src="/assets/icons/streamer-for-hire.svg" alt="" loading="lazy" class="h-9 w-9"/>
</span>
<h3 class="text-xl font-semibold text-white">Streamer for hire</h3>
</div>
<p class="text-sm leading-relaxed text-zinc-300">Ønsker du at FjOlsen skal streame på vegne av din merkevare? Han er tilgjengelig for co-streams, produktlanseringer og kampanjer – der ditt budskap blir formidlet på en autentisk og engasjerende måte til tusenvis av følgere.</p>
</div>
<div class="flex h-full flex-col gap-4 rounded-2xl border border-white/10 bg-[#101a33]/80 p-6 shadow-[0_16px_32px_rgba(6,14,35,0.45)]">
<div class="flex items-center gap-3">
<span class="grid h-12 w-12 place-content-center rounded-xl bg-gradient-to-br from-[#13A0F9] to-[#FF2F9C] text-black">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-graduation-cap h-6 w-6">
<path d="M21.42 10.922a1 1 0 0 0-.019-1.838L12.83 5.18a2 2 0 0 0-1.66 0L2.6 9.08a1 1 0 0 0 0 1.832l8.57 3.908a2 2 0 0 0 1.66 0z">
</path>
<path d="M22 10v6">
</path>
<path d="M6 12.5V16a6 3 0 0 0 12 0v-3.5">
</path>
</svg>
</span>
<h3 class="text-xl font-semibold text-white">Coaching</h3>
</div>
<p class="text-sm leading-relaxed text-zinc-300">I FjOlsenbanden finner du flere av Norges dyktigste Fortnite-spillere. Sammen tilbyr vi 1-til-1 coaching for barn og unge som ønsker å utvikle seg som spillere – med fokus på strategi, samarbeid, kommunikasjon og trygg nettkultur. Ta kontakt hvis du ønsker mer informasjon eller vil booke en økt.</p>
</div>
</div>
</div>
</section>
<section id="kontakt" class="mt-20 px-6" style="order:5">
<div class="mx-auto max-w-5xl space-y-6 rounded-3xl border border-white/10 bg-[#161f33]/90 p-8 text-center shadow-2xl">
<h2 class="text-3xl font-bold">Kontakt oss</h2>
<p class="text-zinc-300">Har du spørsmål om medlemskap, samarbeid eller events? Send oss en melding så kommer vi tilbake til deg.</p>
<form class="grid gap-4 text-left md:grid-cols-2">
<div>
<label class="mb-1 block text-sm font-semibold text-zinc-200" for="name">Navn</label>
<input id="name" name="name" type="text" required="" class="w-full rounded-xl border border-white/15 bg-white/5 px-4 py-3 text-sm text-white placeholder-zinc-400 focus:outline-none focus:ring-2 focus:ring-[#13A0F9]"/>
</div>
<div>
<label class="mb-1 block text-sm font-semibold text-zinc-200" for="email">E-post</label>
<input id="email" name="email" type="email" required="" class="w-full rounded-xl border border-white/15 bg-white/5 px-4 py-3 text-sm text-white placeholder-zinc-400 focus:outline-none focus:ring-2 focus:ring-[#13A0F9]"/>
</div>
<div class="md:col-span-2">
<label class="mb-1 block text-sm font-semibold text-zinc-200" for="message">Melding</label>
<textarea id="message" name="message" rows="4" required="" class="w-full rounded-xl border border-white/15 bg-white/5 px-4 py-3 text-sm text-white placeholder-zinc-400 focus:outline-none focus:ring-2 focus:ring-[#13A0F9]">
</textarea>
</div>
<div class="md:col-span-2 flex flex-col gap-2 text-sm text-zinc-400 md:flex-row md:items-center md:justify-between">
<span>Vi svarer så snart vi kan, som regel innen 1–2 virkedager.</span>
<button type="submit" class="inline-flex items-center justify-center font-semibold transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-60 bg-zinc-900 text-white hover:bg-zinc-800 focus-visible:ring-zinc-900 h-11 px-6 text-base rounded-2xl rounded-full bg-gradient-to-r from-[#13A0F9] to-[#FF2F9C] px-6 font-semibold text-white shadow-[0_16px_28px_rgba(19,160,249,0.35)] transition hover:from-[#0d8bd6] hover:to-[#e12585]">Send melding</button>
</div>
</form>
</div>
</section>
</main>
<footer class="mt-auto border-t border-white/10 py-8 text-center text-sm text-zinc-500">
<div class="flex flex-col items-center justify-center gap-2 text-sm md:flex-row">
<span>© 2025 Fjolsenbanden. Alle rettigheter reservert.</span>
<a href="/admin" class="flex items-center gap-2 font-medium text-zinc-300 transition hover:text-white">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-user-cog h-4 w-4" aria-hidden="true">
<circle cx="18" cy="15" r="3">
</circle>
<circle cx="9" cy="7" r="4">
</circle>
<path d="M10 15H6a4 4 0 0 0-4 4v2">
</path>
<path d="m21.7 16.4-.9-.3">
</path>
<path d="m15.2 13.9-.9-.3">
</path>
<path d="m16.6 18.7.3-.9">
</path>
<path d="m19.1 12.2.3-.9">
</path>
<path d="m19.6 18.7-.4-1">
</path>
<path d="m16.8 12.3-.4-1">
</path>
<path d="m14.3 16.6 1-.4">
</path>
<path d="m20.7 13.8 1-.4">
</path>
</svg>
<span>Admin</span>
</a>
</div>
</footer>
</div>
</div>
    <script>

(function () {
  var navToggle = document.querySelector('[data-nav-toggle]');
  var navMenu = document.querySelector('[data-nav-menu]');
  var navOverlay = document.querySelector('[data-nav-overlay]');
  var navToggleIcons = navToggle ? navToggle.querySelectorAll('[data-nav-toggle-icon]') : [];
  var navToggleLabel = navToggle ? navToggle.querySelector('[data-nav-toggle-label]') : null;

  var setNavToggleState = function (isOpen) {
    if (!navToggle) {
      return;
    }
    navToggle.setAttribute('aria-expanded', String(isOpen));
    navToggle.setAttribute('aria-label', isOpen ? 'Lukk meny' : 'Åpne meny');
    if (navToggleLabel) {
      navToggleLabel.textContent = isOpen ? 'Lukk meny' : 'Åpne meny';
    }
    navToggleIcons.forEach(function (icon) {
      var shouldShow = icon.getAttribute('data-nav-toggle-icon') === (isOpen ? 'close' : 'open');
      icon.classList.toggle('hidden', !shouldShow);
    });
  };

  var openNav = function () {
    if (!navMenu) {
      return;
    }
    navMenu.classList.remove('hidden');
    navMenu.classList.add('block');
    if (navOverlay) {
      navOverlay.classList.remove('hidden');
      navOverlay.classList.add('block');
    }
    setNavToggleState(true);
  };

  var closeNav = function () {
    if (!navMenu) {
      return;
    }
    navMenu.classList.add('hidden');
    navMenu.classList.remove('block');
    if (navOverlay) {
      navOverlay.classList.add('hidden');
      navOverlay.classList.remove('block');
    }
    setNavToggleState(false);
  };

  if (navToggle && navMenu) {
    navToggle.addEventListener('click', function () {
      var isOpen = navToggle.getAttribute('aria-expanded') === 'true';
      if (isOpen) {
        closeNav();
      } else {
        openNav();
      }
    });
  }

  if (navOverlay) {
    navOverlay.addEventListener('click', closeNav);
  }

  if (navMenu) {
    navMenu.querySelectorAll('[data-nav-close]').forEach(function (link) {
      link.addEventListener('click', closeNav);
    });
  }

  window.addEventListener('resize', function () {
    if (window.innerWidth >= 768) {
      closeNav();
    }
  });

  window.addEventListener('keydown', function (event) {
    if (event.key === 'Escape') {
      closeNav();
    }
  });

  document.querySelectorAll('[data-scroll-to]').forEach(function (button) {
    button.addEventListener('click', function (event) {
      var target = button.getAttribute('data-scroll-to');
      if (!target) {
        return;
      }
      var anchor = document.querySelector(target);
      if (!anchor) {
        return;
      }
      event.preventDefault();
      anchor.scrollIntoView({ behavior: 'smooth' });
    });
  });

  var overlay = document.querySelector('[data-preview-overlay]');
  var frame = document.querySelector('[data-preview-frame]');
  var timer = document.querySelector('[data-preview-timer]');
  var unmuteButton = document.querySelector('[data-video-unmute]');
  if (overlay && frame && timer && unmuteButton) {
    var remaining = parseInt(timer.textContent || '60', 10) || 60;
    var interval = window.setInterval(function () {
      remaining = Math.max(remaining - 1, 0);
      timer.textContent = String(remaining);
      if (remaining === 0) {
        window.clearInterval(interval);
      }
    }, 1000);

    var enableSound = function () {
      overlay.remove();
      window.clearInterval(interval);
      try {
        var url = new URL(frame.src);
        url.searchParams.set('muted', 'false');
        frame.src = url.toString();
      } catch (error) {
        frame.src = frame.src.replace('muted=true', 'muted=false');
      }
    };

    unmuteButton.addEventListener('click', function (event) {
      event.preventDefault();
      enableSound();
    });
  }
})();

    </script>
  </body>
</html>
