<?php
// This file is automatically generated by scripts/sync-index-php.mjs. Do not edit directly.
?>
<!DOCTYPE html>
<html lang="no">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Fjolsenbanden – Fargerikt gaming-community</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@500;600;700;800;900&display=swap" rel="stylesheet" />
    <style>
      body {
        font-family: 'Nunito', system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
        background-color: #0e0b1a;
      }
    </style>
  </head>
  <body class="text-white">
    <div id="fjolsenbanden-home" class="min-h-screen">
<div class="relative min-h-screen overflow-x-hidden bg-gradient-to-b from-[#0e0b1a] via-[#151f2c] to-[#0e0b1a] text-white">
<div class="pointer-events-none absolute inset-0" style="background:radial-gradient(circle at 20% 20%, rgba(0,206,255,0.2), transparent 60%)">
</div>
<nav class="relative z-50 flex items-center justify-between px-6 py-4">
<div class="flex items-center gap-2">
<div class="grid h-10 w-10 place-content-center rounded-xl bg-[#00CFFF] font-bold text-black">FB</div>
<span class="hidden text-lg font-semibold sm:block">Fjolsenbanden</span>
</div>
<ul class="hidden gap-6 text-sm font-medium md:flex">
<li>
<a class="transition-colors duration-150 hover:text-[#00CFFF]" href="#">Hjem</a>
</li>
<li>
<a class="transition-colors duration-150 hover:text-[#00CFFF]" href="#live">Live</a>
</li>
<li>
<a class="transition-colors duration-150 hover:text-[#00CFFF]" href="#premier">Premier</a>
</li>
<li>
<a class="transition-colors duration-150 hover:text-[#00CFFF]" href="#medlemskap">Medlemskap</a>
</li>
<li>
<a class="transition-colors duration-150 hover:text-[#00CFFF]" href="#giles">Giles</a>
</li>
<li>
<a class="transition-colors duration-150 hover:text-[#00CFFF]" href="#foreldre">Foreldre</a>
</li>
<li>
<a class="transition-colors duration-150 hover:text-[#00CFFF]" href="#sponsorer">Sponsorer</a>
</li>
</ul>
<button type="button" data-nav-toggle="true" class="rounded-md p-2 transition hover:bg-white/10 md:hidden" aria-label="Toggle navigation" aria-expanded="false">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-menu h-6 w-6">
<line x1="4" x2="20" y1="12" y2="12">
</line>
<line x1="4" x2="20" y1="6" y2="6">
</line>
<line x1="4" x2="20" y1="18" y2="18">
</line>
</svg>
</button>
<ul data-nav-menu="true" class="absolute right-4 top-full mt-2 hidden flex-col gap-3 rounded-xl border border-white/10 bg-[#1f2940] p-4 text-sm shadow-lg transition md:hidden">
<li>
<a href="#" class="block rounded-md px-4 py-2 transition hover:bg-white/10" data-nav-close="true">Hjem</a>
</li>
<li>
<a href="#live" class="block rounded-md px-4 py-2 transition hover:bg-white/10" data-nav-close="true">Live</a>
</li>
<li>
<a href="#premier" class="block rounded-md px-4 py-2 transition hover:bg-white/10" data-nav-close="true">Premier</a>
</li>
<li>
<a href="#medlemskap" class="block rounded-md px-4 py-2 transition hover:bg-white/10" data-nav-close="true">Medlemskap</a>
</li>
<li>
<a href="#giles" class="block rounded-md px-4 py-2 transition hover:bg-white/10" data-nav-close="true">Giles</a>
</li>
<li>
<a href="#foreldre" class="block rounded-md px-4 py-2 transition hover:bg-white/10" data-nav-close="true">Foreldre</a>
</li>
<li>
<a href="#sponsorer" class="block rounded-md px-4 py-2 transition hover:bg-white/10" data-nav-close="true">Sponsorer</a>
</li>
</ul>
</nav>
<section class="mt-6 space-y-6 px-6 text-center">
<h1 class="text-4xl font-extrabold sm:text-5xl">Spill glede for hele familien med <span class="text-[#00CFFF]">Fjolsenbanden</span>
</h1>
<p class="mx-auto max-w-3xl text-base text-zinc-300 sm:text-lg">Trygge streams, ukentlige turneringer og en leken verden for barn og unge. Foreldre logger inn via Vipps for enkel, trygg verifisering.</p>
<div class="flex flex-wrap justify-center gap-4">
<button type="button" class="inline-flex items-center justify-center font-semibold transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-60 bg-zinc-900 text-white hover:bg-zinc-800 focus-visible:ring-zinc-900 h-11 px-6 text-base rounded-2xl rounded-full bg-[#00CFFF] px-6 text-black hover:bg-[#00bcd4]" data-scroll-to="#medlemskap">Meld inn barn</button>
<button type="button" class="inline-flex items-center justify-center font-semibold transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-60 border border-zinc-200 bg-white text-zinc-900 hover:bg-zinc-50 focus-visible:ring-zinc-200 h-11 px-6 text-base rounded-2xl rounded-full border-white/20 px-6 hover:bg-white/10" data-scroll-to="#live">Se neste stream</button>
</div>
<div class="mt-4 flex justify-center gap-6 text-sm text-zinc-400">
<span>3200+ følgere på Twitch</span>
<span>4200+ følgere på TikTok</span>
<span>2500+ medlemmer i Discord</span>
</div>
</section>
<section id="live" class="relative mt-12 px-6">
<div class="mx-auto grid max-w-7xl items-start gap-8 lg:grid-cols-3">
<div class="space-y-4 lg:col-span-2">
<div class="relative overflow-hidden rounded-2xl border border-white/10 shadow-2xl">
<span class="absolute left-3 top-3 rounded-full bg-rose-500 px-4 py-1 text-xs font-semibold text-white shadow animate-pulse">🔴 LIVE</span>
<iframe data-preview-frame="true" src="https://player.twitch.tv/?channel=fjolsenbanden&amp;parent=fjolsenbanden.setaei.com&amp;muted=true" title="Fjolsenbanden Twitch Player" allowfullscreen="" class="aspect-video w-full bg-black">
</iframe>
<div data-preview-overlay="true" class="absolute inset-0 flex flex-col items-center justify-center gap-4 bg-black/70 p-6 text-center">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-play h-12 w-12 text-[#00CFFF]">
<polygon points="6 3 20 12 6 21 6 3">
</polygon>
</svg>
<p class="text-sm text-zinc-300">1-minutt forhåndsvisning –<span data-preview-timer="true" class="ml-1">60</span>s igjen</p>
<button type="button" class="inline-flex items-center justify-center font-semibold transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-60 bg-zinc-900 text-white hover:bg-zinc-800 focus-visible:ring-zinc-900 h-11 px-6 text-base rounded-2xl rounded-full bg-[#00CFFF] px-6 text-black hover:bg-[#00bcd4]" data-video-unmute="true">Se full stream</button>
<div class="flex gap-3 text-xs text-zinc-400">
<span>eller fortsett på<a href="https://www.twitch.tv/fjolsenbanden" target="_blank" rel="noopener noreferrer" class="ml-1 text-[#00CFFF]">Twitch</a>
</span>
<span>|</span>
<span>
<a href="https://youtube.com/@fjolsenbanden" target="_blank" rel="noopener noreferrer" class="text-[#00CFFF]">YouTube</a>
</span>
</div>
</div>
</div>
<div class="flex flex-wrap justify-center gap-4">
<a href="https://www.twitch.tv/fjolsenbanden" target="_blank" rel="noopener noreferrer" class="flex items-center gap-2 rounded-full border border-white/10 bg-white/10 px-4 py-2 text-sm transition duration-200 hover:-translate-y-1 hover:bg-white/20 hover:shadow-lg focus:outline-none focus:ring-2 focus:ring-[#00CFFF] active:scale-95">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-twitch h-5 w-5 text-purple-500">
<path d="M21 2H3v16h5v4l4-4h5l4-4V2zm-10 9V7m5 4V7">
</path>
</svg>
<span>Twitch</span>
</a>
<a href="https://youtube.com/@fjolsenbanden" target="_blank" rel="noopener noreferrer" class="flex items-center gap-2 rounded-full border border-white/10 bg-white/10 px-4 py-2 text-sm transition duration-200 hover:-translate-y-1 hover:bg-white/20 hover:shadow-lg focus:outline-none focus:ring-2 focus:ring-[#00CFFF] active:scale-95">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-youtube h-5 w-5 text-red-500">
<path d="M2.5 17a24.12 24.12 0 0 1 0-10 2 2 0 0 1 1.4-1.4 49.56 49.56 0 0 1 16.2 0A2 2 0 0 1 21.5 7a24.12 24.12 0 0 1 0 10 2 2 0 0 1-1.4 1.4 49.55 49.55 0 0 1-16.2 0A2 2 0 0 1 2.5 17">
</path>
<path d="m10 15 5-3-5-3z">
</path>
</svg>
<span>YouTube</span>
</a>
<a href="https://www.tiktok.com/@fjolsenbanden" target="_blank" rel="noopener noreferrer" class="flex items-center gap-2 rounded-full border border-white/10 bg-white/10 px-4 py-2 text-sm transition duration-200 hover:-translate-y-1 hover:bg-white/20 hover:shadow-lg focus:outline-none focus:ring-2 focus:ring-[#00CFFF] active:scale-95">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-smartphone h-5 w-5 text-pink-500">
<rect width="14" height="20" x="5" y="2" rx="2" ry="2">
</rect>
<path d="M12 18h.01">
</path>
</svg>
<span>TikTok</span>
</a>
<a href="https://www.facebook.com/fjolsenbanden" target="_blank" rel="noopener noreferrer" class="flex items-center gap-2 rounded-full border border-white/10 bg-white/10 px-4 py-2 text-sm transition duration-200 hover:-translate-y-1 hover:bg-white/20 hover:shadow-lg focus:outline-none focus:ring-2 focus:ring-[#00CFFF] active:scale-95">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-facebook h-5 w-5 text-blue-500">
<path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z">
</path>
</svg>
<span>Facebook Gaming</span>
</a>
</div>
</div>
<div class="flex max-h-[640px] flex-col rounded-2xl border border-white/10 bg-[#1f2940] p-4">
<h3 class="mb-3 flex items-center gap-2 font-semibold text-cyan-300">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-message-circle h-4 w-4">
<path d="M7.9 20A9 9 0 1 0 4 16.1L2 22Z">
</path>
</svg> Live chat</h3>
<div class="flex-1 space-y-3 overflow-y-auto pr-1 text-sm">
<div class="rounded-lg bg-white/5 px-3 py-2">
<span class="mr-2 font-semibold text-cyan-300">Lina</span>
<span class="text-zinc-200">Haha, den bossen var vilt!</span>
</div>
<div class="rounded-lg bg-white/5 px-3 py-2">
<span class="mr-2 font-semibold text-cyan-300">Jonas</span>
<span class="text-zinc-200">Gleder meg til premie-trekningen 🔥</span>
</div>
<div class="rounded-lg bg-white/5 px-3 py-2">
<span class="mr-2 font-semibold text-cyan-300">Sara</span>
<span class="text-zinc-200">Hei fra TikTok 😎</span>
</div>
<div class="rounded-lg bg-white/5 px-3 py-2">
<span class="mr-2 font-semibold text-cyan-300">Marius</span>
<span class="text-zinc-200">Bra lyd i dag!</span>
</div>
</div>
<input type="text" placeholder="Skriv en kommentar..." class="mt-3 w-full rounded-lg border border-white/20 bg-white/10 px-3 py-2 text-sm text-white placeholder-zinc-400 outline-none focus:ring-2 focus:ring-[#00CFFF]"/>
</div>
</div>
</section>
<section id="medlemskap" class="mt-20 px-6 text-center">
<h2 class="mb-4 text-3xl font-bold">Velg ditt medlemskap</h2>
<p class="mx-auto mb-8 max-w-2xl text-zinc-300">Bli med i Fjolsenbanden og lås opp premier, turneringer og unike perks. Foreldre verifiserer via Vipps.</p>
<div class="mx-auto grid max-w-7xl gap-8 md:grid-cols-3">
<div class="rounded-2xl border border-zinc-200 bg-white shadow-sm rounded-2xl border bg-[#1f2940] shadow-lg transition-transform hover:-translate-y-1 border-green-400/40 ring-green-400/50">
<div class="p-6">
<h3 class="text-lg font-semibold flex items-center gap-2 text-white">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-gift h-6 w-6">
<rect x="3" y="8" width="18" height="4" rx="1">
</rect>
<path d="M12 8v13">
</path>
<path d="M19 12v7a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2v-7">
</path>
<path d="M7.5 8a2.5 2.5 0 0 1 0-5A4.8 8 0 0 1 12 8a4.8 8 0 0 1 4.5-5 2.5 2.5 0 0 1 0 5">
</path>
</svg> Gratis</h3>
</div>
<div class="px-6 pb-6 space-y-4">
<div class="text-3xl font-bold text-white">0 kr/mnd</div>
<ul class="space-y-2 text-sm text-zinc-300">
<li class="flex items-center gap-2">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-trophy h-4 w-4 text-[#00CFFF]">
<path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6">
</path>
<path d="M18 9h1.5a2.5 2.5 0 0 0 0-5H18">
</path>
<path d="M4 22h16">
</path>
<path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22">
</path>
<path d="M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22">
</path>
<path d="M18 2H6v7a6 6 0 0 0 12 0V2Z">
</path>
</svg> Tilgang til Discord</li>
<li class="flex items-center gap-2">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-trophy h-4 w-4 text-[#00CFFF]">
<path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6">
</path>
<path d="M18 9h1.5a2.5 2.5 0 0 0 0-5H18">
</path>
<path d="M4 22h16">
</path>
<path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22">
</path>
<path d="M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22">
</path>
<path d="M18 2H6v7a6 6 0 0 0 12 0V2Z">
</path>
</svg> Ukentlige streams</li>
<li class="flex items-center gap-2">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-trophy h-4 w-4 text-[#00CFFF]">
<path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6">
</path>
<path d="M18 9h1.5a2.5 2.5 0 0 0 0-5H18">
</path>
<path d="M4 22h16">
</path>
<path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22">
</path>
<path d="M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22">
</path>
<path d="M18 2H6v7a6 6 0 0 0 12 0V2Z">
</path>
</svg> Felles events</li>
</ul>
<button type="button" class="inline-flex items-center justify-center font-semibold transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-60 bg-zinc-900 text-white hover:bg-zinc-800 focus-visible:ring-zinc-900 h-11 px-6 text-base rounded-2xl w-full rounded-full bg-[#00CFFF] text-black hover:bg-[#00bcd4]">Velg</button>
</div>
</div>
<div class="rounded-2xl border border-zinc-200 bg-white shadow-sm rounded-2xl border bg-[#1f2940] shadow-lg transition-transform hover:-translate-y-1 border-cyan-400/40 ring-cyan-400/50">
<div class="p-6">
<h3 class="text-lg font-semibold flex items-center gap-2 text-white">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-gift h-6 w-6">
<rect x="3" y="8" width="18" height="4" rx="1">
</rect>
<path d="M12 8v13">
</path>
<path d="M19 12v7a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2v-7">
</path>
<path d="M7.5 8a2.5 2.5 0 0 1 0-5A4.8 8 0 0 1 12 8a4.8 8 0 0 1 4.5-5 2.5 2.5 0 0 1 0 5">
</path>
</svg> Premie</h3>
</div>
<div class="px-6 pb-6 space-y-4">
<div class="text-3xl font-bold text-white">49 kr/mnd</div>
<ul class="space-y-2 text-sm text-zinc-300">
<li class="flex items-center gap-2">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-trophy h-4 w-4 text-[#00CFFF]">
<path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6">
</path>
<path d="M18 9h1.5a2.5 2.5 0 0 0 0-5H18">
</path>
<path d="M4 22h16">
</path>
<path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22">
</path>
<path d="M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22">
</path>
<path d="M18 2H6v7a6 6 0 0 0 12 0V2Z">
</path>
</svg> Alle Gratis-tilbud</li>
<li class="flex items-center gap-2">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-trophy h-4 w-4 text-[#00CFFF]">
<path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6">
</path>
<path d="M18 9h1.5a2.5 2.5 0 0 0 0-5H18">
</path>
<path d="M4 22h16">
</path>
<path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22">
</path>
<path d="M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22">
</path>
<path d="M18 2H6v7a6 6 0 0 0 12 0V2Z">
</path>
</svg> Deltakelse i premier</li>
<li class="flex items-center gap-2">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-trophy h-4 w-4 text-[#00CFFF]">
<path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6">
</path>
<path d="M18 9h1.5a2.5 2.5 0 0 0 0-5H18">
</path>
<path d="M4 22h16">
</path>
<path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22">
</path>
<path d="M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22">
</path>
<path d="M18 2H6v7a6 6 0 0 0 12 0V2Z">
</path>
</svg> Eksklusive quests</li>
</ul>
<button type="button" class="inline-flex items-center justify-center font-semibold transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-60 bg-zinc-900 text-white hover:bg-zinc-800 focus-visible:ring-zinc-900 h-11 px-6 text-base rounded-2xl w-full rounded-full bg-[#00CFFF] text-black hover:bg-[#00bcd4]">Velg</button>
</div>
</div>
<div class="rounded-2xl border border-zinc-200 bg-white shadow-sm rounded-2xl border bg-[#1f2940] shadow-lg transition-transform hover:-translate-y-1 border-amber-400/40 ring-amber-400/50">
<div class="p-6">
<h3 class="text-lg font-semibold flex items-center gap-2 text-white">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-gift h-6 w-6">
<rect x="3" y="8" width="18" height="4" rx="1">
</rect>
<path d="M12 8v13">
</path>
<path d="M19 12v7a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2v-7">
</path>
<path d="M7.5 8a2.5 2.5 0 0 1 0-5A4.8 8 0 0 1 12 8a4.8 8 0 0 1 4.5-5 2.5 2.5 0 0 1 0 5">
</path>
</svg> Sponsor</h3>
</div>
<div class="px-6 pb-6 space-y-4">
<div class="text-3xl font-bold text-white">299 kr/mnd</div>
<ul class="space-y-2 text-sm text-zinc-300">
<li class="flex items-center gap-2">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-trophy h-4 w-4 text-[#00CFFF]">
<path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6">
</path>
<path d="M18 9h1.5a2.5 2.5 0 0 0 0-5H18">
</path>
<path d="M4 22h16">
</path>
<path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22">
</path>
<path d="M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22">
</path>
<path d="M18 2H6v7a6 6 0 0 0 12 0V2Z">
</path>
</svg> Alle Premie-tilbud</li>
<li class="flex items-center gap-2">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-trophy h-4 w-4 text-[#00CFFF]">
<path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6">
</path>
<path d="M18 9h1.5a2.5 2.5 0 0 0 0-5H18">
</path>
<path d="M4 22h16">
</path>
<path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22">
</path>
<path d="M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22">
</path>
<path d="M18 2H6v7a6 6 0 0 0 12 0V2Z">
</path>
</svg> Merkevare-synlighet</li>
<li class="flex items-center gap-2">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-trophy h-4 w-4 text-[#00CFFF]">
<path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6">
</path>
<path d="M18 9h1.5a2.5 2.5 0 0 0 0-5H18">
</path>
<path d="M4 22h16">
</path>
<path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22">
</path>
<path d="M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22">
</path>
<path d="M18 2H6v7a6 6 0 0 0 12 0V2Z">
</path>
</svg> VIP support</li>
<li class="flex items-center gap-2">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-trophy h-4 w-4 text-[#00CFFF]">
<path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6">
</path>
<path d="M18 9h1.5a2.5 2.5 0 0 0 0-5H18">
</path>
<path d="M4 22h16">
</path>
<path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22">
</path>
<path d="M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22">
</path>
<path d="M18 2H6v7a6 6 0 0 0 12 0V2Z">
</path>
</svg> Egne events</li>
</ul>
<button type="button" class="inline-flex items-center justify-center font-semibold transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-60 bg-zinc-900 text-white hover:bg-zinc-800 focus-visible:ring-zinc-900 h-11 px-6 text-base rounded-2xl w-full rounded-full bg-[#00CFFF] text-black hover:bg-[#00bcd4]">Velg</button>
</div>
</div>
</div>
</section>
<section class="mt-20 px-6 text-center">
<h2 class="mb-4 text-3xl font-bold">Et levende community</h2>
<p class="mx-auto mb-8 max-w-xl text-zinc-300">Fjolsenbanden vokser hver dag. Se hvor mange vi er og bli en del av eventyret!</p>
<div class="mx-auto grid max-w-5xl gap-6 sm:grid-cols-2 md:grid-cols-4">
<div class="flex flex-col items-center space-y-3 rounded-2xl border border-white/10 bg-[#1f2940] p-6 text-center shadow-md">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-users h-8 w-8 text-[#00CFFF]">
<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2">
</path>
<circle cx="9" cy="7" r="4">
</circle>
<path d="M22 21v-2a4 4 0 0 0-3-3.87">
</path>
<path d="M16 3.13a4 4 0 0 1 0 7.75">
</path>
</svg>
<div class="text-2xl font-extrabold text-white">3.2k</div>
<div class="text-sm text-zinc-300">Twitch følgere</div>
</div>
<div class="flex flex-col items-center space-y-3 rounded-2xl border border-white/10 bg-[#1f2940] p-6 text-center shadow-md">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-users h-8 w-8 text-[#00CFFF]">
<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2">
</path>
<circle cx="9" cy="7" r="4">
</circle>
<path d="M22 21v-2a4 4 0 0 0-3-3.87">
</path>
<path d="M16 3.13a4 4 0 0 1 0 7.75">
</path>
</svg>
<div class="text-2xl font-extrabold text-white">4.2k</div>
<div class="text-sm text-zinc-300">TikTok følgere</div>
</div>
<div class="flex flex-col items-center space-y-3 rounded-2xl border border-white/10 bg-[#1f2940] p-6 text-center shadow-md">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-users h-8 w-8 text-[#00CFFF]">
<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2">
</path>
<circle cx="9" cy="7" r="4">
</circle>
<path d="M22 21v-2a4 4 0 0 0-3-3.87">
</path>
<path d="M16 3.13a4 4 0 0 1 0 7.75">
</path>
</svg>
<div class="text-2xl font-extrabold text-white">2.5k</div>
<div class="text-sm text-zinc-300">Discord medlemmer</div>
</div>
<div class="flex flex-col items-center space-y-3 rounded-2xl border border-white/10 bg-[#1f2940] p-6 text-center shadow-md">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-users h-8 w-8 text-[#00CFFF]">
<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2">
</path>
<circle cx="9" cy="7" r="4">
</circle>
<path d="M22 21v-2a4 4 0 0 0-3-3.87">
</path>
<path d="M16 3.13a4 4 0 0 1 0 7.75">
</path>
</svg>
<div class="text-2xl font-extrabold text-white">50+</div>
<div class="text-sm text-zinc-300">Live seere</div>
</div>
</div>
</section>
<section id="premier" class="mt-20 px-6 text-center">
<h2 class="mb-4 text-3xl font-bold">Premier &amp; Sponsorer</h2>
<p class="mx-auto mb-8 max-w-2xl text-zinc-300">Vi samarbeider med ledende merkevarer for å gi deg fantastiske premier. Hver måned trekker vi nye vinnere!</p>
<div class="mx-auto mb-10 grid max-w-7xl gap-8 md:grid-cols-3">
<div class="rounded-2xl border border-zinc-200 bg-white shadow-sm rounded-2xl border border-white/10 bg-[#1f2940] shadow-lg">
<div class="p-6">
<h3 class="text-lg font-semibold text-white">Lenovo</h3>
</div>
<div class="px-6 pb-6 text-sm text-zinc-300">Legion gaming headset</div>
</div>
<div class="rounded-2xl border border-zinc-200 bg-white shadow-sm rounded-2xl border border-white/10 bg-[#1f2940] shadow-lg">
<div class="p-6">
<h3 class="text-lg font-semibold text-white">Samsung</h3>
</div>
<div class="px-6 pb-6 text-sm text-zinc-300">Odyssey 27&quot; skjerm</div>
</div>
<div class="rounded-2xl border border-zinc-200 bg-white shadow-sm rounded-2xl border border-white/10 bg-[#1f2940] shadow-lg">
<div class="p-6">
<h3 class="text-lg font-semibold text-white">Philips</h3>
</div>
<div class="px-6 pb-6 text-sm text-zinc-300">Hue startpakke</div>
</div>
</div>
<div id="sponsorer" class="flex flex-wrap justify-center gap-6">
<span class="rounded-xl border border-white/20 bg-white/5 px-4 py-2 text-sm text-white/80 transition hover:bg-white/10">Lenovo</span>
<span class="rounded-xl border border-white/20 bg-white/5 px-4 py-2 text-sm text-white/80 transition hover:bg-white/10">Samsung</span>
<span class="rounded-xl border border-white/20 bg-white/5 px-4 py-2 text-sm text-white/80 transition hover:bg-white/10">Philips</span>
<span class="rounded-xl border border-white/20 bg-white/5 px-4 py-2 text-sm text-white/80 transition hover:bg-white/10">NKI</span>
<span class="rounded-xl border border-white/20 bg-white/5 px-4 py-2 text-sm text-white/80 transition hover:bg-white/10">Microsoft</span>
</div>
</section>
<section id="giles" class="mt-20 px-6">
<div class="mx-auto grid max-w-6xl gap-8 lg:grid-cols-[1.7fr_1fr]">
<div class="space-y-6 rounded-3xl border border-white/10 bg-[#161f33]/90 p-8 shadow-2xl">
<div class="inline-flex items-center gap-2 rounded-full bg-cyan-500/10 px-3 py-1 text-xs font-semibold uppercase tracking-wide text-cyan-300">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-sparkles h-4 w-4">
<path d="M9.937 15.5A2 2 0 0 0 8.5 14.063l-6.135-1.582a.5.5 0 0 1 0-.962L8.5 9.936A2 2 0 0 0 9.937 8.5l1.582-6.135a.5.5 0 0 1 .963 0L14.063 8.5A2 2 0 0 0 15.5 9.937l6.135 1.581a.5.5 0 0 1 0 .964L15.5 14.063a2 2 0 0 0-1.437 1.437l-1.582 6.135a.5.5 0 0 1-.963 0z">
</path>
<path d="M20 3v4">
</path>
<path d="M22 5h-4">
</path>
<path d="M4 17v2">
</path>
<path d="M5 18H3">
</path>
</svg> Ukens spotlight</div>
<div class="space-y-2">
<h2 class="text-3xl font-bold text-white">Møt Giles</h2>
<p class="text-sm uppercase tracking-wide text-cyan-300">Game Master &amp; trygghetsvert</p>
</div>
<p class="max-w-3xl text-base text-zinc-300">Giles leder de familievennlige streamene våre med et våkent blikk på både chat og spillflyt. Han sørger for at alle føler seg sett, og at konkurransene holder et positivt tempo for alle aldre.</p>
<ul class="space-y-3 text-sm text-zinc-300">
<li class="flex items-start gap-3">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-sparkles mt-0.5 h-4 w-4 flex-shrink-0 text-cyan-300">
<path d="M9.937 15.5A2 2 0 0 0 8.5 14.063l-6.135-1.582a.5.5 0 0 1 0-.962L8.5 9.936A2 2 0 0 0 9.937 8.5l1.582-6.135a.5.5 0 0 1 .963 0L14.063 8.5A2 2 0 0 0 15.5 9.937l6.135 1.581a.5.5 0 0 1 0 .964L15.5 14.063a2 2 0 0 0-1.437 1.437l-1.582 6.135a.5.5 0 0 1-.963 0z">
</path>
<path d="M20 3v4">
</path>
<path d="M22 5h-4">
</path>
<path d="M4 17v2">
</path>
<path d="M5 18H3">
</path>
</svg>
<span>Sertifisert barne- og ungdomsarbeider med fokus på digital trygghet</span>
</li>
<li class="flex items-start gap-3">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-sparkles mt-0.5 h-4 w-4 flex-shrink-0 text-cyan-300">
<path d="M9.937 15.5A2 2 0 0 0 8.5 14.063l-6.135-1.582a.5.5 0 0 1 0-.962L8.5 9.936A2 2 0 0 0 9.937 8.5l1.582-6.135a.5.5 0 0 1 .963 0L14.063 8.5A2 2 0 0 0 15.5 9.937l6.135 1.581a.5.5 0 0 1 0 .964L15.5 14.063a2 2 0 0 0-1.437 1.437l-1.582 6.135a.5.5 0 0 1-.963 0z">
</path>
<path d="M20 3v4">
</path>
<path d="M22 5h-4">
</path>
<path d="M4 17v2">
</path>
<path d="M5 18H3">
</path>
</svg>
<span>Planlegger ukentlige quester og koordinere premier sammen med partnere</span>
</li>
<li class="flex items-start gap-3">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-sparkles mt-0.5 h-4 w-4 flex-shrink-0 text-cyan-300">
<path d="M9.937 15.5A2 2 0 0 0 8.5 14.063l-6.135-1.582a.5.5 0 0 1 0-.962L8.5 9.936A2 2 0 0 0 9.937 8.5l1.582-6.135a.5.5 0 0 1 .963 0L14.063 8.5A2 2 0 0 0 15.5 9.937l6.135 1.581a.5.5 0 0 1 0 .964L15.5 14.063a2 2 0 0 0-1.437 1.437l-1.582 6.135a.5.5 0 0 1-.963 0z">
</path>
<path d="M20 3v4">
</path>
<path d="M22 5h-4">
</path>
<path d="M4 17v2">
</path>
<path d="M5 18H3">
</path>
</svg>
<span>Moderator på Discord med null-toleranse for toksisk oppførsel</span>
</li>
</ul>
<div class="rounded-2xl border border-cyan-500/20 bg-cyan-500/10 p-4 text-sm text-cyan-100">
<strong class="block text-cyan-200">Fun fact</strong>
<p class="mt-2 text-zinc-100">Favorittspill: Kreative Minecraft-bygg og co-op eventyr. Giles er også kjent for å droppe random high-fives i chatten!</p>
</div>
</div>
<div class="rounded-2xl border border-zinc-200 bg-white shadow-sm flex flex-col justify-between rounded-3xl border border-white/10 bg-[#101727]/90 text-left">
<div class="p-6">
<h3 class="text-lg font-semibold flex items-center gap-2 text-cyan-300">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-quote h-5 w-5">
<path d="M3 21c3 0 7-1 7-8V5c0-1.25-.756-2.017-2-2H4c-1.25 0-2 .75-2 1.972V11c0 1.25.75 2 2 2 1 0 1 0 1 1v1c0 1-1 2-2 2s-1 .008-1 1.031V20c0 1 0 1 1 1z">
</path>
<path d="M15 21c3 0 7-1 7-8V5c0-1.25-.757-2.017-2-2h-4c-1.25 0-2 .75-2 1.972V11c0 1.25.75 2 2 2h.75c0 2.25.25 4-2.75 4v3c0 1 0 1 1 1z">
</path>
</svg> Giles sier</h3>
</div>
<div class="px-6 pb-6 space-y-6 text-zinc-200">
<p class="text-lg italic">“Jeg vil at alle skal føle seg velkommen – både spillere, foreldre og de som er helt nye i gaming.”</p>
<div class="rounded-2xl border border-white/10 bg-white/5 p-4 text-sm text-zinc-300">
<p>Si hei til Giles i chatten under neste stream – han svarer alltid på spørsmål og kan tipse om hvilke quester som passer for både nye og erfarne medlemmer.</p>
</div>
</div>
</div>
</div>
</section>
<section id="foreldre" class="mt-20 grid gap-10 px-6 lg:grid-cols-2 lg:items-center">
<div class="space-y-4">
<h2 class="text-3xl font-bold">Informasjon til foreldre</h2>
<p class="text-zinc-300">Som forelder kan du stole på Fjolsenbanden. Vi bruker Vipps for å verifisere alder og innhente samtykke. Ditt barn kan trygt delta i streams, premier og konkurranser – alt innenfor trygge rammer.</p>
<button type="button" class="inline-flex items-center justify-center font-semibold transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-60 bg-zinc-900 text-white hover:bg-zinc-800 focus-visible:ring-zinc-900 h-11 px-6 text-base rounded-2xl rounded-full bg-[#00CFFF] px-6 text-black hover:bg-[#00bcd4]">Logg inn med Vipps</button>
</div>
<div class="rounded-2xl border border-zinc-200 bg-white shadow-sm rounded-2xl border border-white/10 bg-[#1f2940]">
<div class="p-6">
<h3 class="text-lg font-semibold flex items-center gap-2 text-cyan-300">
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-shield-check h-6 w-6">
<path d="M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z">
</path>
<path d="m9 12 2 2 4-4">
</path>
</svg> Trygt og sikkert</h3>
</div>
<div class="px-6 pb-6 space-y-3 text-sm text-zinc-300">
<p>Vipps-innlogging sikrer at voksne verifiserer barna sine.</p>
<p>Alle data lagres trygt og brukes kun til medlemsadministrasjon.</p>
<p>Du har full oversikt over medlemskap og premier via dashbordet.</p>
</div>
</div>
</section>
<footer class="mt-20 border-t border-white/10 py-8 text-center text-sm text-zinc-500">© 2025 Fjolsenbanden. Alle rettigheter reservert.</footer>
</div>
</div>
    <script>

(function () {
  var navToggle = document.querySelector('[data-nav-toggle]');
  var navMenu = document.querySelector('[data-nav-menu]');
  if (navToggle && navMenu) {
    navToggle.addEventListener('click', function () {
      var isOpen = navMenu.classList.contains('flex');
      navMenu.classList.toggle('flex', !isOpen);
      navMenu.classList.toggle('hidden', isOpen);
      navToggle.setAttribute('aria-expanded', String(!isOpen));
    });
    document.querySelectorAll('[data-nav-close]').forEach(function (link) {
      link.addEventListener('click', function () {
        navMenu.classList.remove('flex');
        navMenu.classList.add('hidden');
        navToggle.setAttribute('aria-expanded', 'false');
      });
    });
  }

  document.querySelectorAll('[data-scroll-to]').forEach(function (button) {
    button.addEventListener('click', function (event) {
      var target = button.getAttribute('data-scroll-to');
      if (!target) {
        return;
      }
      var anchor = document.querySelector(target);
      if (!anchor) {
        return;
      }
      event.preventDefault();
      anchor.scrollIntoView({ behavior: 'smooth' });
    });
  });

  var overlay = document.querySelector('[data-preview-overlay]');
  var frame = document.querySelector('[data-preview-frame]');
  var timer = document.querySelector('[data-preview-timer]');
  var unmuteButton = document.querySelector('[data-video-unmute]');
  if (overlay && frame && timer && unmuteButton) {
    var remaining = parseInt(timer.textContent || '60', 10) || 60;
    var interval = window.setInterval(function () {
      remaining = Math.max(remaining - 1, 0);
      timer.textContent = String(remaining);
      if (remaining === 0) {
        window.clearInterval(interval);
      }
    }, 1000);

    var enableSound = function () {
      overlay.remove();
      window.clearInterval(interval);
      try {
        var url = new URL(frame.src);
        url.searchParams.set('muted', 'false');
        frame.src = url.toString();
      } catch (error) {
        frame.src = frame.src.replace('muted=true', 'muted=false');
      }
    };

    unmuteButton.addEventListener('click', function (event) {
      event.preventDefault();
      enableSound();
    });
  }
})();

    </script>
  </body>
</html>
